AWSTemplateFormatVersion: "2010-09-09"
Description: Create a cross-account IAM role for N2G Auditing on NAS Financial Group Account

Parameters:
  lionN2GAuditingAccountId:    #Enter N2G Auditing Account ID 678140435250
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lionN2GAuditingAccountId


Resources:

  policy0:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: IAM role managed policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - trustedadvisor:*
            Resource: '*'

  CrossAccountRole:
    Type: 'AWS::IAM::Role'
    DependsOn:
      - policy0
    Properties:
      Description: IAMcross account role for N2G auditing 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${lionN2GAuditingAccountId}:user/admin' # give access to only admin user
            Action:
              - 'sts:AssumeRole' 
              # sts = security token service
      ManagedPolicyArns:
        - !Ref policy0
       


