AWSTemplateFormatVersion: 2010-09-09
Description: >- # AWS::VPC network stack
  This template will help us create groups and user for the project NAS-Finacial. 
  It will also allow us to add policies to any group or users.
Parameters:
  Password:
    Default: P@ssw0rd
    Description: Here is the universal password for every new user created or added
    Type: String

Resources:
  EngineersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: CloudSpace-Engineers-Lion-Cluster # give a name to this group 1 st Group 
      Path: '/'
      Policies: # list of inline policy documents that are embedded in the group
        - PolicyName: inlineadministrationandnobilling # give a unique name to this policy
          PolicyDocument: # JSON policy document
             Version: '2012-10-17'
             Statement:
                - Sid: Stmt1675279815470
                  Action: aws-portal:*
                  Effect: Deny
                  Resource: "*"
                - Sid: Stmt1675280384537
                  Action: "*"
                  Effect: Allow
                  Resource: "*"
  OperationsGroup:
    Type: 'AWS::IAM::Group'
    Properties:      
      GroupName: NAS-Fanancial-Group-Operation-Team    # give a name to this group 2nd Group 
      Path: '/'
      Policies: # list of inline policy documents that are embedded in the group
        - PolicyName: inlineDeployonus-east-1 # give a unique name to this policy
          PolicyDocument: # JSON policy document
             Version: '2012-10-17'
             Statement: # allow to launch resources only in us-east-1 region
                - Sid: "Stmt1675280384537"
                  Effect: Allow
                  Action: '*'
                  Resource: '*'
                - Sid: Stmt1664033817057
                  Effect: Allow
                  Action:
                   - '*'
                  Resource: '*' 
                  Condition: 
                    StringEquals:
                      aws:RequestedRegion: us-east-1
  SecurityGroup:
    Type: 'AWS::IAM::Group'
    Properties:     
      GroupName: NAS-Financial_Group-Security-Team   # give a name to this group 3rd Group 
      Path: '/'
      ManagedPolicyArns: # list of ARNs of IAM managed policies that you want to attach to the group
        - arn:aws:iam::aws:policy/AdministratorAccess        # provide administrator access to AWS resources
        - arn:aws:iam::aws:policy/job-function/Billing       # provide billing access to all aws resources 

  FirstUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Joseph' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
  SecondUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Kingsley' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
  ThirdUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Rokshana' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
  FourthUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Simon' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
  FifthUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Thomas' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
  SixthUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Ken' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
  SeventhUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'Rachidetou' # give a name to this user
      LoginProfile: # specify a password for this user
        Password: !Ref Password
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - CloudSpace-Engineers-Lion-Cluster
          
        